// <auto-generated />
using IntelboardAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntelboardAPI.Migrations
{
    [DbContext(typeof(IntelboardDbContext))]
    [Migration("20250512083230_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntelboardAPI.Models.Cost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "amount");

                    b.Property<int>("CraftableItemId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "craftableitem id");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "material id");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "resource id");

                    b.HasKey("Id");

                    b.HasIndex("CraftableItemId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ResourceId");

                    b.ToTable("Costs", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "cost");
                });

            modelBuilder.Entity("IntelboardAPI.Models.CraftableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("CraftableItems", (string)null);

                    b
                        .UseTptMappingStrategy()
                        .HasAnnotation("Relational:JsonPropertyName", "craftable item");
                });

            modelBuilder.Entity("IntelboardAPI.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasAnnotation("Relational:JsonPropertyName", "resource");
                });

            modelBuilder.Entity("IntelboardAPI.Models.Ammunition", b =>
                {
                    b.HasBaseType("IntelboardAPI.Models.CraftableItem");

                    b.Property<int>("CrateAmount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "crate amount");

                    b.Property<int>("Damage")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "damage");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.ToTable("Ammunitions", (string)null);
                });

            modelBuilder.Entity("IntelboardAPI.Models.Material", b =>
                {
                    b.HasBaseType("IntelboardAPI.Models.CraftableItem");

                    b.Property<int>("CrateAmount")
                        .HasColumnType("int");

                    b.ToTable("Materials", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "material");
                });

            modelBuilder.Entity("IntelboardAPI.Models.Cost", b =>
                {
                    b.HasOne("IntelboardAPI.Models.CraftableItem", "CraftableItem")
                        .WithMany("ProductionCost")
                        .HasForeignKey("CraftableItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelboardAPI.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IntelboardAPI.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CraftableItem");

                    b.Navigation("Material");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("IntelboardAPI.Models.Ammunition", b =>
                {
                    b.HasOne("IntelboardAPI.Models.CraftableItem", null)
                        .WithOne()
                        .HasForeignKey("IntelboardAPI.Models.Ammunition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntelboardAPI.Models.Material", b =>
                {
                    b.HasOne("IntelboardAPI.Models.CraftableItem", null)
                        .WithOne()
                        .HasForeignKey("IntelboardAPI.Models.Material", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntelboardAPI.Models.CraftableItem", b =>
                {
                    b.Navigation("ProductionCost");
                });
#pragma warning restore 612, 618
        }
    }
}
