// <auto-generated />
using FoxholeIntelboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoxholeIntelboard.Migrations
{
    [DbContext(typeof(IntelboardDBContext))]
    [Migration("20250430085127_CraftableItems")]
    partial class CraftableItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoxholeIntelboard.Models.Ammunition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrateAmount")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SpecialProperties")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ammunitions");
                });

            modelBuilder.Entity("FoxholeIntelboard.Models.Cost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmmunitionId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AmmunitionId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Cost");
                });

            modelBuilder.Entity("FoxholeIntelboard.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversionRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefinedFromId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RefinedFromId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("FoxholeIntelboard.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("FoxholeIntelboard.Models.Cost", b =>
                {
                    b.HasOne("FoxholeIntelboard.Models.Ammunition", null)
                        .WithMany("ProductionCost")
                        .HasForeignKey("AmmunitionId");

                    b.HasOne("FoxholeIntelboard.Models.Material", null)
                        .WithMany("ProductionCost")
                        .HasForeignKey("MaterialId");
                });

            modelBuilder.Entity("FoxholeIntelboard.Models.Material", b =>
                {
                    b.HasOne("FoxholeIntelboard.Models.Resource", "RefinedFrom")
                        .WithMany()
                        .HasForeignKey("RefinedFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefinedFrom");
                });

            modelBuilder.Entity("FoxholeIntelboard.Models.Ammunition", b =>
                {
                    b.Navigation("ProductionCost");
                });

            modelBuilder.Entity("FoxholeIntelboard.Models.Material", b =>
                {
                    b.Navigation("ProductionCost");
                });
#pragma warning restore 612, 618
        }
    }
}
