name: FoxholeIntelBoardBuild

on: workflow_dispatch

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - name: build repository
      uses: actions/checkout@v4.2.2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: '9'

    - name: Build exproject
      run: dotnet build FoxholeIntelboard.sln
